dist: bionic
language: python
python:
  - "3.8.0"

services:
  - docker

notifications:
  slack: seleniumhq:Kx5MB7T51SPMpbBMYfvxNW4q


script:
  - cd Base
  - docker build -t zhangdber/docker-selenium-base:arm64
    
    
arch:
  - arm64
