dist: bionic
language: python
python:
  - "3.8.0"

services:
  - docker


script:
  - cd Base
  - docker build -t zhangdber/docker-selenium-base:arm64 .
  - docker login -u zhangdber -p 123456aaa docker.io
  - docker push zhangdber/docker-selenium-base:arm64
    
    
arch:
  - arm64
