dist: bionic
language: python
python:
  - "3.8.0"

services:
  - docker


script:
  - cd NodeChrome
  - wget https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk11u-2020-08-15-05-58/OpenJDK11U-jdk_aarch64_linux_hotspot_2020-08-15-05-58.tar.gz
  - docker build -t zhangdber/openjdk11u:arm64 .
  - docker login -u zhangdber -p 123456aaa docker.io
  - docker push zhangdber/openjdk11u:arm64
    
    
arch:
  - arm64
