dist: bionic
language: python
python:
  - "3.8.0"

services:
  - docker


script:
  - cd NodeChrome
  - wget https://github.com/AdoptOpenJDK/openjdk15-binaries/releases/download/jdk15u-2020-08-15-04-46/OpenJDK15U-jdk_aarch64_linux_hotspot_2020-08-15-04-46.tar.gz
  - docker build -t zhangdber/openjdk15u:arm64 .
  - docker login -u zhangdber -p 123456aaa docker.io
  - docker push zhangdber/openjdk15u:arm64
    
    
arch:
  - arm64
